# html lang
language: 
- zh-CN
- en

# main menu navigation
menu:
  首页: /
  归档: /archives

# scripts loaded in the end of the body
scripts:
- /js/common.js

widgets:
- category
- tagcloud
- archive
- recent_posts

less:
  options:
    javascriptEnabled: true
