# Favicon
favicon: ''

# 头像
avatar: ''

# html lang
language: 
- zh-CN
- en

# main menu navigation
menu:
  Home: /

# scripts loaded in the end of the body
scripts:
- /js/common.mjs

widgets:
- category
- tagcloud
- archive
- recent_posts

less:
  options:
    javascriptEnabled: true

# giscus 评论系统
# https://giscus.app/
giscus:
  enable: false
  repo: kianfang/hexo-theme-kian
  repo_id: R_kgDOJnV4AQ
  category: General
  category_id: DIC_kwDOJnV4Ac4CW0uc
  mapping: specific
  strict: 1
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme
  loading: lazy
